spring.application.name: jmanagewallbag

app:
  url:
  grant_type:
  client_id:
  client_secret:
  username:
  password:


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate.ddl-auto: none
    #show-sql: true
    #defer-datasource-initialization: false



  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

