spring.application.name: jmanagewallbag

app:
  url:
  grant_type:
  client_id:
  client_secret:
  username:
  password:
  page-size: 100
  batch-insert-size: 10
  fichier-pocket:


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate.ddl-auto: none

    properties:
      hibernate:
        generate_statistics: true
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
    #show-sql: true
    #defer-datasource-initialization: false




  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

